version: '3.8'
services:
  nuxt-front:
    build: ./nuxt
    ports:
      - 9000:3000
    volumes:
      - ./nuxt/src:/workspace
    working_dir: /workspace
  go-back:
    build: ./go
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./go/src:/workspace
    working_dir: /workspace
  db-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      #TZ: ${TIMEZONE}
    volumes:
      - db-storage:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306
    platform: linux/x86_64
volumes:
  db-storage:
